---
- name: Install EPEL Repository
  package:
    name: epel-release
    state: present
  when: ansible_facts['python']['version'].major == '2'

- name: Install required packages
  package:
    name:
    - libvirt-admin
    - libvirt-client
    - "{{ 'python3-pip' if ansible_facts['python']['version'].major == 3 else 'python-pip' }}"
    state: present
