---
- include_tasks: "install-{{ ansible_facts.os_family }}.yml"

- name: Install required Python packages
  pip:
    name: openshift

- name: Enable nested virtualization (Intel)
  lineinfile:
    line: options kvm_intel nested=1
    path: /etc/modprobe.d/kvm.conf
    create: yes
    state: present
  when: kubevirt_enable_nested | bool
  register: kubevirt_intel_nested

- name: Enable nested virtualization (AMD)
  lineinfile:
    line: options kvm_amd nested=1
    path: /etc/modprobe.d/kvm.conf
    create: yes
    state: present
  when: kubevirt_enable_nested | bool
  register: kubevirt_amd_nested

- name: Reload kernel modules
  systemd:
    name: systemd-modules-load
    daemon_reload: yes
    state: restarted
    enabled: yes
  when: >-
    kubevirt_amd_nested.changed
    or
    kubevirt_intel_nested.changed
